"""
routing_tools.py — Orchestrator tools for pipeline routing decisions and env var output.
"""
import json
import os
from datetime import datetime, timezone
from pathlib import Path

import requests
import urllib3
from langchain.tools import tool

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

RESULTS_DIR = Path(os.environ.get("ENTERPRISE_ROOT", ".")) / "results"
WORKSPACE = Path(os.environ.get("ENTERPRISE_ROOT", ".")) / "agent_workspace"

VALID_ACTIONS = ["retrain", "partial_retrain", "fast_promote", "emergency_rollback", "skip"]
VALID_WORKFLOWS = ["full-canary", "fast-promote", "emergency-rollback", "none"]
VALID_SEVERITIES = ["critical", "high", "medium", "low", "none"]

ARGO_API_URL = os.environ.get("ARGO_URL", os.environ.get("ARGO_API_URL", "http://localhost:2746"))
ARGO_TOKEN = os.environ.get("ARGO_TOKEN", "")
ARGO_NAMESPACE = os.environ.get("ARGO_NAMESPACE", "argo")


@tool
def decide_routing(decision_json: str) -> str:
    """
    Write pipeline_decision.json — the Orchestrator's final routing call.
    Input JSON: {
      "round": 1,
      "action": "retrain",               # retrain/partial_retrain/fast_promote/emergency_rollback/skip
      "models_to_retrain": ["injection"], # list of detector names
      "severity": "high",                 # critical/high/medium/low/none
      "confidence": 0.91,                 # float 0-1
      "argo_workflow": "full-canary",     # full-canary/fast-promote/emergency-rollback/none
      "reason": "...",                    # free text
      "next_attack_families": []          # families for next round
    }
    """
    try:
        decision = json.loads(decision_json)
    except json.JSONDecodeError as e:
        return f"ERROR: invalid JSON — {e}"

    action = decision.get("action", "")
    if action not in VALID_ACTIONS:
        return f"ERROR: action must be one of {VALID_ACTIONS}, got '{action}'"

    workflow = decision.get("argo_workflow", "none")
    if workflow not in VALID_WORKFLOWS:
        return f"ERROR: argo_workflow must be one of {VALID_WORKFLOWS}, got '{workflow}'"

    severity = decision.get("severity", "none")
    if severity not in VALID_SEVERITIES:
        return f"ERROR: severity must be one of {VALID_SEVERITIES}, got '{severity}'"

    decision["timestamp"] = datetime.now(timezone.utc).isoformat()
    decision.setdefault("models_to_retrain", [])
    decision.setdefault("next_attack_families", [])
    decision.setdefault("confidence", 0.0)

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = RESULTS_DIR / "pipeline_decision.json"
    out_path.write_text(json.dumps(decision, indent=2), encoding="utf-8")

    # Also write to agent_workspace for Orchestrator self-reference
    WORKSPACE.mkdir(parents=True, exist_ok=True)
    (WORKSPACE / "orchestrator_decision.json").write_text(json.dumps(decision, indent=2), encoding="utf-8")

    return f"Decision written — action={action}, severity={severity}, workflow={workflow}, confidence={decision.get('confidence')}"


@tool
def set_env_vars(vars_json: str) -> str:
    """
    Write pipeline env vars to results/pipeline_env.sh (sourced by Jenkins).
    Input JSON: {"AI_ACTION": "retrain", "ARGO_WORKFLOW": "full-canary", "SEVERITY": "high"}
    Jenkins reads this file and exports vars before triggering Argo.
    """
    try:
        env_vars = json.loads(vars_json)
    except json.JSONDecodeError as e:
        return f"ERROR: invalid JSON — {e}"

    required = ["AI_ACTION", "ARGO_WORKFLOW", "SEVERITY"]
    missing = [k for k in required if k not in env_vars]
    if missing:
        return f"ERROR: missing required vars {missing}"

    lines = ["#!/bin/bash", "# Auto-generated by Orchestrator Agent — do not edit manually"]
    for k, v in env_vars.items():
        lines.append(f'export {k}="{v}"')

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = RESULTS_DIR / "pipeline_env.sh"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return f"Env vars written to results/pipeline_env.sh: {env_vars}"


@tool
def trigger_argo(trigger_json: str) -> str:
    """
    Submit an Argo Workflow via REST API.
    Input JSON: {"workflow": "full-canary", "round": 1, "dry_run": false}
    Requires ARGO_API_URL and ARGO_TOKEN env vars in production.
    dry_run=true returns the payload without POSTing.
    """
    try:
        args = json.loads(trigger_json)
    except json.JSONDecodeError as e:
        return f"ERROR: invalid JSON — {e}"

    workflow = args.get("workflow", "none")
    round_num = args.get("round", 0)
    dry_run = args.get("dry_run", False)

    if workflow == "none":
        return "Workflow=none — no Argo submission needed for this round."

    model_path = args.get("model_path", f"models/v{round_num}/")
    payload = {
        "namespace": ARGO_NAMESPACE,
        "resourceKind": "WorkflowTemplate",
        "resourceName": workflow,
        "submitOptions": {
            "parameters": [
                {"name": "round", "value": str(round_num)},
                {"name": "model_path", "value": model_path},
            ],
            "labels": {"round": str(round_num), "workflow": workflow},
        },
    }

    if dry_run:
        return json.dumps({"dry_run": True, "would_post_to": f"{ARGO_API_URL}/api/v1/workflows/{ARGO_NAMESPACE}/submit", "payload": payload}, indent=2)

    if not ARGO_TOKEN:
        return "ERROR: ARGO_TOKEN not set. Cannot submit to Argo in production mode."

    try:
        resp = requests.post(
            f"{ARGO_API_URL}/api/v1/workflows/{ARGO_NAMESPACE}/submit",
            headers={"Authorization": f"Bearer {ARGO_TOKEN}", "Content-Type": "application/json"},
            json=payload,
            verify=False,
            timeout=30,
        )
        if resp.ok:
            name = resp.json().get("metadata", {}).get("name", "unknown")
            return f"Argo workflow submitted: {name} (workflow={workflow}, round={round_num})"
        return f"ERROR: Argo API {resp.status_code}: {resp.text[:300]}"
    except Exception as e:
        return f"ERROR: could not reach Argo API — {e}"
